name: TrendFurnace
description: Real-world trending content, generated daily.
baseurl: '/trendfurnace-blog'
url: 'https://monsieur-nico.github.io'

defaults:
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: post
plugins:
  - jekyll-sitemap
